### ISSUE TITLE
pubKeyByte方法修改

### ISSUE THREAD

**Issue by KendoCross** [farmerx/gorsa#1]
感谢大神的分享，我在使用过程中，总是出现问题。检查了好久，直接把如下代码调整了下。可以正常使用。out 默认初始化长度为0。由于对整个加密解密原理不清楚，所以不知道是不是个案。
pubKeyByte 即公钥加密或解密byte方法中的以下代码，
iv := make([]byte, k)
out := bytes.NewBuffer(iv)
我修改为
iv := make([]byte, 0)
out := bytes.NewBuffer(iv)

**Comment by heviye** [comment]
k := (pri.N.BitLen() + 7) / 8
其中的+7是什么意思？求指教！

**Comment by KendoCross** [comment]
> k := (pri.N.BitLen() + 7) / 8
> 其中的+7是什么意思？求指教！

**Comment by KendoCross** [comment]
使得结果始终比pri.N.BitLen()/8得整数值大1
